- .dependabot/config.yml
- LICENSE
- README.md
- package.json
- Updated ReadMe.md to be more P&I specific
- Updated license
- Updated dependabot to run monthly instead of daily
- Updated project name in package.json
> Minor project setup changes

- .gitignore
- README.md
- docker-compose.yml
- package.json
Fixed docker config. Updated ReadMe/Package.json/.gitIgnore
> Fixed docker config. Updated ReadMe/Package.json/.gitIgnore

- package.json
- yarn.lock
Added relevant resolutions for packages introducing HIGH vulnerabilities.
Reduced vulnerabilities from:
_29 vulnerabilities found - Packages audited: 1584
Severity: 1 Low | 22 Moderate | 6 High_
To:
_12 vulnerabilities found - Packages audited: 1583
Severity: 12 Moderate_
```
[ ] Yes
[x] No
```
> Removed all high vulnerabilities as reported by Yarn Audit

- README.md
n/a
Update README instructions for running end-to-end test
```
[ ] Yes
[x] No
```
> readme: update e2e instructions

- src/main/assets/scss/main.scss
- src/main/views/template.njk
https://tools.hmcts.net/jira/browse/PUB-490
reformat header
css for small screen
added sign-in
```
[ ] Yes
[X] No
```
> pip-490: css for small screen

- Jenkinsfile_CNP
- Jenkinsfile_nightly
- Jenkinsfile_parameterized
- charts/Publishing-information-project-PI/Chart.yaml
- charts/Publishing-information-project-PI/values.yaml
- docker-compose.yml
https://tools.hmcts.net/jira/browse/PUB-403
Following the https://tools.hmcts.net/confluence/pages/viewpage.action?pageId=1504228713 lead to updating the names to match patterns our other services are following that regex is looking for in the sds intergration, therefore renamed values mentioned in the linked page to `pip-frontend`
```
[ ] Yes
[x] No
```
> renamed params and added jenkins files to prep for SDS intergration

- .eslintignore
- .sass-lint.yml
- src/main/assets/scss/accessible-autocomplete.min.scss
- src/main/resources/actions/courtActions.ts
- webpack.config.js
fixed the linting issues, mostly stemmed from the accessible autocomplete, fixed the scss of it and added the js to the lint ignore, also removed the excessive court listing logs
```
[ ] Yes
[ ] No
```
> fixed linting issues and removed excessive logs

- docker-compose.yml
> Revert "changed the image url in dockerfile"

- src/main/controllers/SearchOptionController.ts
Use redirect instead of render on the POST requests in order to prevent form resubmission (PRG pattern)
```
[ ] Yes
[x] No
```
> fix - use redirect instead of render to prevent form resubmission error

- src/main/controllers/SearchOptionController.ts
- src/test/unit/controllers/SearchOptionController.test.ts
Refactor test for redirect
```
[ ] Yes
[x] No
```
> Search Options For Resubmit Tests

- src/test/unit/controllers/SearchController.test.ts
Added extra tests to the search controller to make sure the url reflects valid results for location and jurisdiction
```
[ ] Yes
[ ] No
```
> added location and jurisdidction tests to the search controller

- jest.config.js
- src/test/routes/not-found.test.ts
- src/test/unit/views/not-found.test.ts
Added tests for not found page, excluded modules file tests
```
[ ] Yes
[X] No
```
> PUB-673 Not found page tests

- src/main/controllers/OtpLoginTestingController.ts
- src/main/routes/routes.ts
- src/main/views/otp-login-testing.njk
https://tools.hmcts.net/jira/browse/PUB-741
Adding testing page to try out hooking up with OTP (See https://docs.microsoft.com/en-us/azure/active-directory-b2c/customize-ui-with-html?pivots=b2c-custom-policy for details)
The api div in the code can be used by Azure. This page will only be temporary to try this out.
```
[ ] Yes
[x] No
```
> PUB-741-Added-Testing-Page-For-UI

- package.json
- src/main/routes/routes.ts
- yarn.lock
https://tools.hmcts.net/jira/browse/PUB-741
Added CORS for the testing page for testing Azure B2C
```
[ ] Yes
[x] No
```
> PUB-741 - Added cors

- src/main/routes/routes.ts
https://tools.hmcts.net/jira/browse/PUB-741
Further CORS changes for testing + update to origin
```
[ ] Yes
[x] No
```
> PUB-741 - Further CORS changes

- src/main/modules/helmet/index.ts
- src/main/routes/routes.ts
- src/main/views/otp-login-testing.njk
https://tools.hmcts.net/jira/browse/PUB-741
Added styling link to enable styling for the otp-login-testing page.
```
[ ] Yes
[x] No
```
> PUB 741 - Added styling

- src/main/controllers/OtpLoginController.ts
- src/main/views/otp-login.njk
- src/test/unit/controllers/OtpLoginController.test.ts
- src/test/unit/views/otp-login.test.ts
https://tools.hmcts.net/jira/browse/PUB-693
Updated UI to match the new screenshot + removed validation of the text from the frontend.
[
](url)
```
[ ] Yes
[x] No
```
> PUB 693 - UI OTP Update

- package.json
> updated dependency causing a11y to fail

- yarn.lock
update yarn lock to fix the build process
```
[ ] Yes
[x] No
```
> update yarn.lock file to fix the build

- src/main/service/inputFilterService.ts
- src/test/unit/service/inputFilterService.test.ts
https://tools.hmcts.net/jira/browse/PUB-729
JSONArray was being used which was an import from pupeteer which was being worked out of the project so we needed a replacement for JSONArray, replaced with a alias for string and number called Serializable[], once the model for listings is completed we can replace with that return type
```
[ ] Yes
[x] No
```
> Pub 729 jsonarray

- src/main/views/template.njk
- src/test/unit/views/home.test.ts
https://tools.hmcts.net/jira/browse/PUB-740
Added 'Subscription' button to header of all pages
> PUB-740: Added subscription button in header

- src/main/views/template.njk
- src/test/e2e/Helpers/Selectors.ts
- src/test/e2e/PageObjects/OtpLoginTesting.page.ts
- src/test/e2e/pageobjects/Home.page.ts
- src/test/e2e/tests/specs.test.ts
Updated e2e tests to include "Subscriptions" header button that was missed in original (merged) PR of PUB-740
> PUB-740: Added e2e test for subscriptions button

- src/test/e2e/tests/specs.test.ts
https://tools.hmcts.net/jira/browse/PUB-740
Fix - change page type
```
[ ] Yes
[x] No
```
> change page type

- charts/pip-frontend/Chart.yaml
- charts/pip-frontend/values.dev.template.yaml
- charts/pip-frontend/values.yaml
> Setup communication front end and business rules

- src/main/assets/scss/main.scss
- yarn.lock
https://tools.hmcts.net/jira/browse/PUB-748
Further UI styling to make box appear in a block
```
[ ] Yes
[x] No
```
> Pub 748 OTP UI

- package.json
- src/main/assets/scss/main.scss
- src/main/controllers/AlphabeticalSearchController.ts
- src/main/routes/routes.ts
- src/main/service/courtService.ts
- src/main/service/filterService.ts
- src/main/views/alphabetical-search.njk
- src/test/unit/controllers/AlphabeticalSearchController.test.ts
- src/test/unit/service/courtService.test.ts
- src/test/unit/views/alphabetical-search.test.ts
- yarn.lock
https://tools.hmcts.net/jira/browse/PUB-696
added filter service to alphabetical search page and removed the hearing counter
```
[ ] Yes
[ ] No
```
> Pub-696 - added filter service to alphabetical search page

- src/main/models/request/PipRequest.ts
- src/main/resources/locales/en/status-description.json
- src/main/resources/mocks/StatusDescription.json
- src/main/resources/requests/searchDescriptionRequests.ts
- src/main/views/status-description.njk
- src/test/unit/requests/searchDescriptionRequests.test.ts
Reverts hmcts/pip-frontend#133
> Revert "Pub 721 latest master and use mock data"

- src/main/assets/scss/main.scss
https://tools.hmcts.net/jira/browse/PUB-748
CSS change to add colour and styling to error text on the OTP page.
```
[ ] Yes
[x] No
```
> PUB 748 - Added Error colour and styling

- src/main/views/court-name-search.njk
https://tools.hmcts.net/jira/browse/PUB-733
fix for the selection counter
```
[ ] Yes
[x] No
```
> Fix - Court Search Counter

- src/main/resources/requests/statusDescriptionRequests.ts
- src/main/service/statusDescriptionService.ts
- src/test/a11y/a11y.ts
- src/test/unit/mocks/StatusDescription.json
- src/test/unit/requests/searchDescriptionRequests.test.ts
- src/test/unit/requests/statusDescriptionRequests.test.ts
- src/test/unit/service/statusDescriptionService.test.ts
- src/test/unit/views/status-description.test.ts
Mock courteventglossary API call which causes a11y tests to fail
```
[ ] Yes
[x] No
```
> Fix: mock a11y api request for court events glossary

- src/main/resources/locales/en/view-option.json
- src/main/views/view-option.njk
- src/test/unit/views/view-option.test.ts
https://tools.hmcts.net/jira/browse/PUB-857
Add hint for radio button
```
[ ] Yes
[X] No
```
> PUB-857 - Added hint for radio button

- src/main/routes/routes.ts
Remove production checks
```
[ ] Yes
[x] No
```
> pub-833: remove production checks

- charts/pip-frontend/values.dev.template.yaml
https://tools.hmcts.net/jira/browse/PUB-833
Unset OIDC in Dev to use mock strategy
```
[ ] Yes
[x] No
```
> Unset OIDC in dev

- package.json
- src/main/app.ts
- yarn.lock
Potential session auth fix on staging
```
[ ] Yes
[ ] No
```
> Staging Fix Auth

- src/main/routes/routes.ts
- src/test/unit/views/logout.test.ts
N/A
Updated so that logging in to mock session takes you to the home page.
Also updated logout to use cookies
```
[ ] Yes
[x] No
```
> Updated Mock Session Redirect + Logout

- src/main/views/template.njk
changed the nav bar links to poiint to prototype
```
[ ] Yes
[ ] No
```
> changed the links for account and subscriptions to point to prototype

- src/main/views/alphabetical-search.njk
- src/main/views/case-name-search-results.njk
https://tools.hmcts.net/jira/browse/PUB-885
Added form resubmit handler
```
[ ] Yes
[x] No
```
> pub-885: Error on returning to the A-Z from a list post filtering

- src/main/resources/locales/en/session-management.json
- src/main/routes/routes.ts
- src/main/views/session-management.njk
https://tools.hmcts.net/jira/browse/PUB-902
- rename button label to "Start Testing"
- point button and successful login to alphabetical-search page
```
[ ] Yes
[x] No
```
> pub-902: Session set up improvements

- src/main/resources/locales/en/list-option.json
- src/main/resources/locales/en/standard-list.json
- src/main/resources/locales/en/view-option.json
- src/test/unit/views/list-option.test.ts
- src/test/unit/views/view-option.test.ts
https://tools.hmcts.net/jira/browse/PUB-888
Updated Typo's in the FE.
Related BE PR: https://github.com/hmcts/pip-data-management/pull/29
```
[ ] Yes
[x] No
```
> Updated typo's

- src/main/views/session-management.njk
adding space for master container rebuild
```
[ ] Yes
[ ] No
```
> added a space to try retrigger master container rebuild

- src/main/resources/locales/en/search.json
changed the hint text in search page to a valid court
```
[ ] Yes
[ ] No
```
> changed hint text for search

- jest.a11y.config.js
As per Accessibility call increasing timeout to 30s 
https://github.com/pa11y/pa11y#timeout-number
```
[ ] Yes
[x] No
```
> PUB-924: Accessibility timeout

- src/main/resources/locales/en/view-option.json
- src/main/views/view-option.njk
- src/test/unit/views/view-option.test.ts
https://tools.hmcts.net/jira/browse/PUB-952
- Add radio button labels
- Update unit tests to reflect the changes
**NOTE**:
Merge to master is intentional as we want to push this change to be included in the UAT
```
[ ] Yes
[x] No
```
> PUB-952 - View option page radio buttons labels

- src/main/resources/locales/en/template.json
- src/main/views/template.njk
https://tools.hmcts.net/jira/browse/PUB-980
Update account home to be home for the signed in users
```
[ ] Yes
[x] No
```
> PUB-980 - Update navigation links

- package.json
- src/main/views/subscription-add.njk
- src/test/e2e/tests/specs.test.ts
- src/test/unit/views/subscription-add.test.ts
- yarn.lock
https://tools.hmcts.net/jira/browse/PUB-871
- re-order add subscription radio options
- reflect re-order changes on the view unit test
- remove e2e error test
```
[ ] Yes
[x] No
```
> PUB-871 - Re-order radio buttons on Subscription Add page

- src/main/views/court-name-search.njk
https://tools.hmcts.net/jira/browse/PUB-937
Prevent form re-submit error on the courts search screen
```
[ ] Yes
[x] No
```
> PUB-937 - Court search resubmission

- yarn.lock
https://tools.hmcts.net/jira/browse/PUB-1020
Fix high vulnerability by upgrading axios dependency packages
```
[ ] Yes
[x] No
```
> PUB-1020:  Vulnerability Fix

- src/main/views/alphabetical-search.njk
- src/main/views/case-name-search-results.njk
- src/main/views/court-name-search.njk
https://tools.hmcts.net/jira/browse/PUB-887
Reset checkboxes when navigating backwards by turning form autocomplete off
**NOTE:** 
Build is failing as SJP court has been added and needs to be filtered from the view will be done with PUB-956 #225 
```
[ ] Yes
[x] No
```
> PUB-887 - Reset Checkboxes

- config/default.json
- src/main/authentication/authRedirect.ts
- src/main/authentication/authentication-config.json
- src/main/controllers/SignInController.ts
- src/main/resources/locales/en/sign-in.json
- src/main/views/sign-in.njk
- src/test/e2e/tests/specs.test.ts
- src/test/routes/sign-in.test.ts
- src/test/unit/controllers/SignInController.test.ts
- src/test/unit/views/sign-in.test.ts
https://tools.hmcts.net/jira/browse/PUB-962
- construct redirect url depending on the environment variable, if none is provided defaults to default values
- add P&I login redirect url
- add tests
**NOTE:**
Environment variable names were set in agreement with Chris P
```
[ ] Yes
[x] No
```
> PUB-962 - P&I redirect URL

- src/test/e2e/tests/specs.test.ts
Add missing subscribe e2e
```
[ ] Yes
[x] No
```
> add pending subscription subscribe e2e tests

- src/main/cacheManager.ts
- src/test/e2e/tests/specs.test.ts
- src/test/unit/assets/cacheManager.test.ts
- wdio.conf.js
Redis debugging on staging
```
[ ] Yes
[x] No
```
> Add logging for staging and additional e2e tests

- charts/pip-frontend/Chart.yaml
> Trigger master build to Staging

- src/main/controllers/SignInController.ts
- src/main/routes/routes.ts
- src/test/unit/controllers/SignInController.test.ts
n/a
- Add logging around sign in
- change policy variable on sign in
```
[ ] Yes
[x] No
```
> Add auth logging and change login param on sign in

- src/main/resources/locales/en/case-name-search-results.json
- src/main/resources/locales/en/interstitial.json
- src/main/resources/locales/en/search.json
- src/test/unit/views/case-name-search-results.test.ts
- src/test/unit/views/interstitial.test.ts
changed locales content
```
[ ] Yes
[x] No
```
> updated content for hint court, results pluralisation and capital letter

- src/main/resources/locales/en/subscription-add.json
- src/main/resources/requests/dataManagementRequests.ts
- src/main/routes/routes.ts
- src/main/views/daily-cause-list.njk
- src/main/views/interstitial.njk
- src/main/views/subscription-add.njk
- src/test/unit/views/daily-cause-list.test.ts
- src/test/unit/views/subscription-add.test.ts
https://tools.hmcts.net/jira/browse/PUB-1105
Amend screens for DAC
```
[ ] Yes
[x] No
```
> PUB-1105 DACUI changes

- src/main/resources/locales/en/create-media-account.json
- src/main/resources/locales/en/manual-upload.json
- src/main/views/manual-upload.njk
- src/test/unit/views/create-media-account.test.ts
- src/test/unit/views/manual-upload.test.ts
https://tools.hmcts.net/jira/browse/PUB-1103
Re order accepted files on file upload fields
```
[ ] Yes
[x] No
```
> PUB-1103 Re-order File Formats

- charts/pip-frontend/Chart.yaml
- charts/pip-frontend/values.yaml
remove the certs from the charts.
```
[ ] Yes
[ x ] No
```
> remove certs from charts

- src/main/service/courtService.ts
- src/test/unit/service/courtService.test.ts
https://tools.hmcts.net/jira/browse/PUB-1107
Add sorting to the courts list again
```
[ ] Yes
[x] No
```
> PUB-1107 - Re-implement sort function

- src/main/controllers/PendingSubscriptionsController.ts
- src/main/controllers/SubscriptionConfirmedController.ts
- src/main/resources/locales/en/pending-subscriptions.json
- src/main/views/pending-subscriptions.njk
- src/test/routes/pending-subscriptions.test.ts
- src/test/routes/subscription-confirmed.test.ts
- src/test/unit/controllers/PendingSubscriptionsController.test.ts
- src/test/unit/controllers/SubscriptionConfirmedController.test.ts
- src/test/unit/views/pending-subscriptions.test.ts
- src/test/unit/views/subscription-confirmed.test.ts
https://tools.hmcts.net/jira/browse/PUB-1017
Add error screen if there are no pending subscriptions and user tries to confirm them
```
[ ] Yes
[x] No
```
> PUB-1017 - Confirm Subscriptions Error Screen

- src/main/resources/locales/en/admin-dashboard.json
- src/test/unit/views/admin-dashboard.test.ts
change admin dashboard content
```
[ ] Yes
[x] No
```
> UT content update on the admin dashboard

- src/main/controllers/ViewOptionController.ts
- src/main/resources/locales/en/view-option.json
- src/main/views/view-option.njk
- src/test/unit/controllers/ViewOptionController.test.ts
- src/test/unit/views/view-option.test.ts
https://tools.hmcts.net/jira/browse/PUB-1162
- remove javascript button disable
- add error summary if no option is selected
- add additional unit test to check if page title matches header title
```
[ ] Yes
[x] No
```
> PUB-1162 - R1 - Error summary on the view option page

- src/main/modules/nunjucks/listUrlLookup.json
https://tools.hmcts.net/jira/browse/PUB-974
Updated URL from summary of publications to link to press list
```
[ ] Yes
[x] No
```
> PUB-974 - Updated Press List

- package.json
n/a
Bump transitive dependency released 6h ago, packages we use have not been updated yet, therefore we are forcing an update
```
[ ] Yes
[x] No
```
> Fix minimist vulnerability 

- src/main/resources/locales/en/interstitial.json
- src/test/unit/views/interstitial.test.ts
https://tools.hmcts.net/jira/browse/PUB-1156
Add `and` to the courts list bullet
```
[ ] Yes
[x] No
```
> PUB-1156 - Add and

- src/main/resources/locales/en/account-home.json
- src/main/resources/locales/en/alphabetical-search.json
- src/main/resources/locales/en/court-name-search.json
- src/main/resources/locales/en/interstitial.json
- src/main/resources/locales/en/pending-subscriptions.json
- src/main/resources/locales/en/search.json
- src/main/resources/locales/en/subscription-add.json
- src/main/resources/locales/en/subscription-confirmed.json
- src/main/resources/locales/en/subscription-management.json
- src/main/views/account-home.njk
- src/main/views/court-name-search.njk
- src/main/views/error.njk
- src/main/views/interstitial.njk
- src/main/views/not-found.njk
- src/main/views/pending-subscriptions.njk
- src/main/views/search.njk
- src/main/views/subscription-add.njk
- src/main/views/subscription-management.njk
- src/test/a11y/a11y.ts
- src/test/unit/views/account-home.test.ts
- src/test/unit/views/alphabetical-search.test.ts
- src/test/unit/views/court-name-search.test.ts
- src/test/unit/views/interstitial.test.ts
- src/test/unit/views/pending-subscriptions.test.ts
- src/test/unit/views/search.test.ts
- src/test/unit/views/subscription-add.test.ts
- src/test/unit/views/subscription-confirmed.test.ts
- src/test/unit/views/subscription-management.test.ts
https://tools.hmcts.net/jira/browse/PUB-1174
Add titles to pages and add unit tests to check whether correct titles are set
```
[ ] Yes
[x] No
```
> PUB-1174 - Change Page Titles

- src/main/resources/locales/en/template.json
- src/main/views/template.njk
- src/test/unit/views/interstitial.test.ts
https://tools.hmcts.net/jira/browse/PUB-1159
- update footer links
- add unit test to check name value pairs
```
[ ] Yes
[x] No
```
> PUB-1159 - Footer Links

- src/main/authentication/authentication.ts
- src/main/resources/requests/dataManagementRequests.ts
- src/main/resources/requests/utils/axiosConfig.ts
- src/main/routes/routes.ts
- src/test/unit/authentication/Authentication.test.ts
- src/test/unit/requests/dataManagementRequests.test.ts
n/a
Change urls to point to demo instead of staging
```
[ ] Yes
[x] No
```
> Point to Demo instead of Staging

- src/main/assets/scss/main.scss
- src/main/resources/locales/en/summary-of-publications.json
- src/main/views/summary-of-publications.njk
https://tools.hmcts.net/jira/browse/PUB-1206
- Content change
- Change h2 tag to paragraph
- Convert links to list of links
- Move hardcoded text to translations
```
[ ] Yes
[x] No
```
> PUB-1206 - Summary of Publications Changes

- src/main/routes/routes.ts
N/A
Fix sonarqube issues in the demo environment
```
[ ] Yes
[x] No
```
> Fix demo issues

- README.md
- src/main/resources/locales/en/search.json
- src/test/e2e/tests/specs.test.ts
https://tools.hmcts.net/jira/browse/PUB-1167
Update the text on court search page.
[ ] Yes
[x] No
> PUB-1167 - Update text on courts search page

- README.md
- charts/pip-frontend/values.yaml
- config/default.json
- src/main/authentication/authRedirect.ts
- src/test/unit/authentication/authRedirect.test.ts
Remove Test secrets
Update B2C with AAD
```
[ ] Yes
[ X ] No
```
> Fix secret

- charts/pip-frontend/Chart.yaml
- charts/pip-frontend/values.yaml
- config/default.json
- src/main/authentication/authRedirect.ts
- src/test/unit/authentication/authRedirect.test.ts
- yarn.lock
Update Secret Names
Remove Test Secrects
```
[ ] Yes
[ x ] No
```
> Update Secrets Names

- src/main/service/filterService.ts
- src/test/e2e/Helpers/Selectors.ts
- src/test/e2e/tests/specs.test.ts
- src/test/unit/service/filterService.test.ts
https://tools.hmcts.net/jira/browse/PUB-1168
Added sorting to Alphabetical search filters.
```
[ ] Yes
[x] No
```
> PUB-1168 - Filter order

- package.json
- src/test/e2e/tests/specs.test.ts
N/A
Fix async dependency
```
[ ] Yes
[x] No
```
> Fix async dependency

- src/main/resources/locales/en/create-media-account.json
- src/main/views/create-media-account.njk
- src/test/e2e/tests/specs.test.ts
- src/test/unit/views/create-media-account.test.ts
https://tools.hmcts.net/jira/browse/PUB-1270
Updated messaging on page create media account page:
```
[ ] Yes
[x] No
```
> PUB-1270 - Updated messaging

- src/main/views/template.njk
- src/test/e2e/Helpers/Selectors.ts
- src/test/unit/assets/banner.tests.ts
https://tools.hmcts.net/jira/browse/PUB-1249
Re-ordered the navigation bar to have email subscriptions after SJP for verified users
```
[ ] Yes
[x] No
```
> PUB 1249 navbar update

- README.md
N/A
Adding readme change to trigger build
```
[ ] Yes
[x] No
```
> Re-trigger master build

- src/main/resources/locales/en/subscription-confirmed.json
- src/main/views/subscription-confirmed.njk
- src/test/e2e/tests/specs.test.ts
- src/test/unit/views/subscription-confirmed.test.ts
https://tools.hmcts.net/jira/browse/PUB-1251
Updated subscription confirmation screen with text changes and links
```
[ ] Yes
[x] No
```
> PUB-1251 - Updated subscription confirmation screen

- src/main/resources/requests/accountManagementRequests.ts
- src/main/resources/requests/utils/axiosConfig.ts
Superagent fix, added back in / to account management requests. Removed / from fixed superagent URLs. 
```
[ ] Yes
[x ] No
```
> Superagent / issue fix

- .github/workflows/on-pr.yml
Add a Temperorary fix for the pre github task.
```
[ ] Yes
[ x ] No
```
> Add Temp fix for Github Task

- .github/workflows/close-pr.yml
- .github/workflows/on-pr.yml
[PUB-1350](https://tools.hmcts.net/jira/browse/PUB-1350)
Fix on PR Task
```
[ ] Yes
[ x ] No
```
> PUB-1350 - Fix On PR Task

- src/main/resources/locales/en/create-admin-account-summary.json
- src/main/views/create-admin-account-summary.njk
- src/test/routes/view-option.test.ts
- src/test/unit/views/create-admin-account-summary.test.ts
https://tools.hmcts.net/jira/browse/PUB-1255
[ ] Yes
[x] No
> PUB-1255 Change admin error

- package.json
- src/main/controllers/DailyCauseListController.ts
- src/main/controllers/SjpPressListController.ts
- src/main/controllers/SjpPublicListController.ts
- src/main/service/publicationService.ts
- src/test/unit/controllers/DailyCauseListController.test.ts
- src/test/unit/controllers/SjpPressListController.test.ts
- src/test/unit/controllers/SjpPublicListController.test.ts
- src/test/unit/mocks/dailyCauseList.json
- src/test/unit/mocks/familyDailyCauseList.json
- src/test/unit/service/publicationService.test.ts
- src/test/unit/views/daily-cause-list.test.ts
- src/test/unit/views/family-daily-cause-list.test.ts
- yarn.lock
https://tools.hmcts.net/jira/browse/PUB-1422
Updated FE to account for UTC timestamps
```
[ ] Yes
[x] No
```
> PUB-1422 - Handling UTC times

- README.md
> hope this works

- src/main/controllers/SjpPressListController.ts
- src/main/controllers/SjpPublicListController.ts
- src/main/controllers/SscsDailyListController.ts
- src/main/modules/nunjucks/listTypeLookup.json
- src/main/modules/nunjucks/listUrlLookup.json
- src/main/resources/locales/bill/sscs-daily-list.json
- src/main/resources/locales/cy/sscs-daily-list.json
- src/main/resources/locales/en/sscs-daily-list.json
- src/main/routes/routes.ts
- src/main/service/dataManipulationService.ts
- src/main/service/manualUploadService.ts
- src/main/service/publicationService.ts
- src/main/views/sscs-daily-list.njk
- src/test/routes/civil-and-family-daily-cause-list.test.ts
- src/test/routes/daily-cause-list.test.ts
- src/test/routes/family-daily-cause-list.test.ts
- src/test/routes/single-justice-procedure-press.test.ts
- src/test/routes/sscs-daily-list.test.ts
- src/test/unit/controllers/DailyCauseListController.test.ts
- src/test/unit/controllers/SscsDailyListController.test.ts
- src/test/unit/mocks/sscsDailyList.json
- src/test/unit/service/dataManipulationService.test.ts
- src/test/unit/service/manualUploadService.test.ts
- src/test/unit/service/publicationService.test.ts
- src/test/unit/views/sscs-daily-list-test.ts
https://tools.hmcts.net/jira/browse/PUB-1260
Added new list template for SSCS daily list
Create new data manipulation service and refactored the publication service.
```
[ ] Yes
[x] No
```
> PUB-1260 SSCS Daily List template

- src/test/e2e/Helpers/Selectors.ts
- src/test/e2e/PageObjects/ManualUpload.page.ts
- src/test/e2e/tests/specs.test.ts
Fix the E2Es
```
[ ] Yes
[x] No
```
> Fix the E2Es

- README.md
- src/main/app.ts
- src/test/unit/views/account-home.test.ts
> readme change

- src/main/resources/locales/en/sign-in.json
- src/test/unit/views/sign-in.test.ts
https://tools.hmcts.net/jira/browse/PUB-1459
Changed this:
To this:
PR will need to be amended later to add Welsh.
```
[ ] Yes
[x] No
```
> PUB-1459 - Radio Button Content Change

- src/main/modules/nunjucks/listTypeLookup.json
https://tools.hmcts.net/jira/browse/PUB-1457
Fixed the issue of "Civil And Family Daily Cause List" having an upper case "a" in "And".
```
[ ] Yes
[x] No
```
> PUB 1457 - Lower case A

- src/main/resources/locales/en/admin-dashboard.json
- src/test/e2e/tests/specs.test.ts
- src/test/unit/views/admin-dashboard.test.ts
https://tools.hmcts.net/jira/browse/PUB-1475
Quick content change from "Admin Dashboard" to "Your Dashboard"
OLD:
NEW:
```
[ ] Yes
[x] No
```
> PUB 1475 - "admin dashboard" to "your dashboard"

- src/main/service/dataManipulationService.ts
- src/test/unit/mocks/familyDailyCauseListWithReorderedPartyMappings.json
- src/test/unit/service/dataManipulationService.test.ts
https://tools.hmcts.net/jira/browse/PUB-1484
Fixed issue wherein JSON order mattered for party roles. Have now got it working as intended with a test to verify.
```
[ ] Yes
[x] No
```
> PUB 1484 overwritten parties fix

- src/main/controllers/CreateAdminAccountSummaryController.ts
- src/main/controllers/MediaAccountApprovalController.ts
- src/main/controllers/MediaAccountRejectionController.ts
- src/main/controllers/RemoveListConfirmationController.ts
- src/main/resources/requests/accountManagementRequests.ts
- src/main/resources/requests/dataManagementRequests.ts
- src/main/resources/requests/publicationRequests.ts
- src/main/resources/requests/subscriptionRequests.ts
- src/main/service/mediaAccountApplicationService.ts
- src/main/service/publicationService.ts
- src/test/routes/remove-list-confirmation.test.ts
- src/test/unit/controllers/CreateAdminAccountSummaryController.test.ts
- src/test/unit/controllers/MediaAccountApprovalController.test.ts
- src/test/unit/controllers/MediaAccountRejectionController.test.ts
- src/test/unit/controllers/RemoveListConfrimationController.test.ts
https://tools.hmcts.net/jira/browse/PUB-1478
Updated to pass through / log user ID where appropriate.
No masking needed in this service
```
[ ] Yes
[x] No
```
> PUB-1478 Update Logging

- src/test/e2e/tests/specs.test.ts
N/A
Fixed E2E tests due to court name change
```
[ ] Yes
[x] No
```
> Fixed E2E tests

- src/main/views/sign-in.njk
- src/test/e2e/tests/specs.test.ts
- src/test/unit/views/sign-in.test.ts
https://tools.hmcts.net/jira/browse/PUB-1518
Commented out the create account link and tests temporarily until we are ready to add it back in.
```
[ ] Yes
[x] No
```
> PUB-1518 Temp remove create account link

- src/main/views/summary-of-publications.njk
- src/test/unit/mocks/summaryOfPublications.json
- src/test/unit/requests/publicationRequests.test.ts
- src/test/unit/views/publication.test.ts
https://tools.hmcts.net/jira/browse/PUB-1505
Sort summary of publications by content date followed by alphabetical order of list type
```
[ ] Yes
[x] No
```
> PUB-1505 Sort summary of publications by content date followed by alphabetical order of list type

- src/main/authentication/authenticationHandler.ts
- src/main/routes/routes.ts
- src/test/unit/authentication/authenticationHandler.test.ts
https://tools.hmcts.net/jira/browse/PUB-1431
Increase auto session closure to 4hrs.
[ ] Yes
[x] No
> Pub 1431 increase admin screen timeout

- src/main/models/consts.ts
N/A
Added .xlsx files to upload
```
[ ] Yes
[x] No
```
> Updated consts file

- src/main/service/sessionManagementService.ts
- src/test/unit/service/sessionManagementService.test.ts
Destroy request session after logged out
Destroy request session after logged out
```
[ ] Yes
[x] No
```
> PUB-1523 Destroy request session after logged out

- package.json
- yarn.lock
N/A
Updated dependency for moment
```
[ ] Yes
[x] No
```
> Updated moment dependency

- src/main/resources/locales/cy/subscription-management.json
https://tools.hmcts.net/jira/browse/PUB-1528
Update Welsh text on subscription management page for "Court or tribunal name"
```
[ ] Yes
[x] No
```
> PUB-1528 Update Welsh text for "Court or tribunal name"

- charts/pip-frontend/Chart.yaml
- charts/pip-frontend/values.yaml
https://tools.hmcts.net/jira/browse/PUB-942
This PR just updates the chart with the new secret so that it can be tested in the Test env
```
[ ] Yes
[x] No
```
> PUB-942 - Updated chart

- wdio.conf.js
Update chrome driver version for e2e tests
```
[ ] Yes
[x] No
```
> Update chrome driver version for e2e tests

- src/main/resources/locales/cy/media-account-approval-confirmation.json
- src/main/resources/locales/cy/media-account-approval.json
- src/main/resources/locales/cy/media-account-rejection-confirmation.json
- src/main/resources/locales/cy/media-account-rejection.json
- src/main/resources/locales/cy/media-account-review.json
- src/main/resources/locales/en/media-account-approval-confirmation.json
- src/main/resources/locales/en/media-account-approval.json
- src/main/resources/locales/en/media-account-rejection-confirmation.json
- src/main/resources/locales/en/media-account-rejection.json
- src/main/resources/locales/en/media-account-review.json
- src/test/unit/views/media-account-approval.test.ts
- src/test/unit/views/media-account-confirmation.test.ts
- src/test/unit/views/media-account-rejection-confirmation.test.ts
- src/test/unit/views/media-account-rejection.test.ts
- src/test/unit/views/media-account-review.test.ts
https://tools.hmcts.net/jira/browse/PUB-1328
Updated media account flow to opens in new window
```
[ ] Yes
[x] No
```
> PUB-1328 - Updated text to opens in new window

- src/main/resources/requests/dataManagementRequests.ts
- src/test/unit/requests/dataManagementRequests.test.ts
https://tools.hmcts.net/jira/browse/PUB-1618
Updated Frontend to use Auth when calling the ref data endpoints
```
[ ] Yes
[x] No
```
> PUB-1618 - Updated ref upload to use auth

- src/main/service/createAccountService.ts
- src/main/views/create-media-account.njk
- src/test/unit/service/createAccountService.test.ts
https://tools.hmcts.net/jira/browse/PUB-1327
Updated so values that are sent in are kept when validation fails.
```
[ ] Yes
[x] No
```
> PUB-1327 Media upload fields should not be wiped

- src/test/e2e/Helpers/Selectors.ts
- src/test/e2e/PageObjects/ManualUpload.page.ts
- src/test/e2e/tests/specs.test.ts
Update the E2Es to use a new test court.
```
[ ] Yes
[x] No
```
> Update E2Es to use test court

- src/main/helpers/dateTimeHelper.ts
- src/main/service/dataManipulationService.ts
- src/main/service/listManipulation/CrimeListsService.ts
- src/main/service/listManipulation/crownWarnedListService.ts
- src/main/service/listManipulation/magistratesStandardListService.ts
- src/main/service/listManipulation/tribunalNationalListsService.ts
- src/main/views/civil-and-family-daily-cause-list.njk
- src/main/views/cop-daily-cause-list.njk
- src/main/views/crown-warned-list.njk
- src/main/views/daily-cause-list.njk
- src/main/views/et-daily-list.njk
- src/main/views/family-daily-cause-list.njk
- src/main/views/iac-daily-list.njk
- src/main/views/primary-health-list.njk
- src/test/unit/helpers/dateTimeHelper.test.ts
- src/test/unit/mocks/civilAndFamilyDailyCauseList.json
- src/test/unit/mocks/copDailyCauseList.json
- src/test/unit/mocks/crimeListParty.json
- src/test/unit/mocks/crownDailyList.json
- src/test/unit/mocks/dailyCauseList.json
- src/test/unit/mocks/familyDailyCauseList.json
- src/test/unit/mocks/iacDailyList.json
- src/test/unit/mocks/magistratesPublicList.json
- src/test/unit/service/dataManipulationService.test.ts
- src/test/unit/service/listManipulation/crimeListsService.test.ts
- src/test/unit/views/crown-daily-list.test.ts
- src/test/unit/views/crown-warned-list.test.ts
- src/test/unit/views/iac-daily-list.test.ts
- src/test/unit/views/magistrates-public-list.test.ts
https://tools.hmcts.net/jira/browse/PUB-1607
Various bug fixes for list template:
- Show start time in 'h:mma' format for IAC daily list, ET daily list and ET fortnightly list
- Use party organisation details for prosecuting authority and defendant representatives for all Crime lists
- Remove case sequence indicator square bracket formatting for:
- Civil daily cause list
- Family daily cause list
- Civil and family daily cause list
- COP daily cause list
- IAC daily list
- Primary health list
- Crown warned list: bold the text for 'Linked cases' and 'Listing notes' on the case tables
- IAC daily list: format the tables per session rather than per court room
```
[ ] Yes
[x] No
```
> PUB-1607 Various bug fixes for list template

- src/test/e2e/PageObjects/ManualUpload.page.ts
- src/test/e2e/tests/specs.test.ts
N/A
Fixed E2E Test Court
```
[ ] Yes
[x] No
```
> Fix E2E tests

- src/main/views/webpack/css.njk
https://tools.hmcts.net/jira/browse/PUB-1724
Removed un required line of code.
```
[ ] Yes
[x] No
```
> PUB-1724 fix 404

- .gitignore
- package.json
- src/test/config.ts
- src/test/end-to-end/functional.conf.js
- src/test/end-to-end/functional.conf.ts
- src/test/end-to-end/shared/random-data.ts
- src/test/end-to-end/steps.d.ts
- src/test/end-to-end/tests/access-home-page.ts
- src/test/end-to-end/tests/custom-steps.ts
- src/test/tsconfig.json
- yarn.lock
https://tools.hmcts.net/jira/browse/PUB-1748
Added CodeceptJs Playwright framework
```
[ ] Yes
[X] No
```
> Pub 1748 Added test framework with CodeceptJs and Playwright

- jest.a11y.config.js
- jest.config.js
- jest.routes.config.js
- package.json
- yarn.lock
N/A
Upgrade Axios to 1.2.1
```
[ ] Yes
[x] No
```
> PUB-1721 - Upgrade Axios

- package.json
- yarn.lock
N/A
Update WDIO and UA Parser
```
[ ] Yes
[x] No
```
> Updated wdio + ua parser

- .github/workflows/update-pr.yml
Auto update PR perform action on conflict.
```
[ ] Yes
[x] No
```
> auto update PR

- package.json
- yarn.lock
Fix security vulnerability CVE-2022-25881
```
[ ] Yes
[x] No
```
> Fix security vulnerability CVE-2022-25881

- src/test/unit/mocks/civilAndFamilyDailyCauseList.json
- src/test/unit/mocks/crownDailyList.json
- src/test/unit/mocks/etDailyList.json
- src/test/unit/mocks/familyDailyCauseList.json
- src/test/unit/mocks/magistratesPublicList.json
- src/test/unit/mocks/sscsDailyList.json
Date time format fixed in json file
```
[ ] Yes
[x] No
```
> Date time format fixed in json file

- src/main/resources/locales/cy/home.json
- src/main/resources/locales/en/home.json
- src/test/unit/views/home.test.ts
https://tools.hmcts.net/jira/browse/PUB-1859
Added in new bullet point for courts
```
[ ] Yes
[x] No
```
> PUB-1859 - Home Page Updates

- .github/workflows/close-pr.yml
Fix syntax error on close PR github action
```
[ ] Yes
[x] No
```
> Fix close PR github action

- package.json
- yarn.lock
Update nunjucks version to 3.2.4 to fix security vulnerability
```
[ ] Yes
[x] No
```
> Update nunjucks version to 3.2.4

- src/test/e2e/PageObjects/DeleteUser.page.ts
- src/test/e2e/PageObjects/ManageUser.page.ts
- src/test/e2e/PageObjects/SystemAdminDashboard.page.ts
- src/test/e2e/PageObjects/UpdateUser.page.ts
- src/test/e2e/PageObjects/UserManagement.page.ts
- src/test/e2e/tests/specs.test.ts
Adding back user management delete user e2e tests
```
[ ] Yes
[x] No
```
> Adding back user management delete user e2e tests

- src/test/end-to-end/shared/shared-functions.ts
- src/test/end-to-end/shared/testingSupportApi.ts
- src/test/end-to-end/tests/admin/manual-upload-flat-test.ts
- src/test/end-to-end/tests/admin/manual-upload-json-test.ts
- src/test/end-to-end/tests/admin/manual-upload-sensitivity-test.ts
- src/test/end-to-end/tests/system-admin/system-admin-audit-log-test.ts
https://tools.hmcts.net/jira/browse/PUB-1892
Add new E2E tests for system admin audit log viewer
```
[ ] Yes
[ ] No
```
> PUB-1892 Add new E2E tests for system admin audit log viewer

- src/test/end-to-end/tests/admin/manual-upload-json-test.ts
https://tools.hmcts.net/jira/browse/PUB-2036
Fix functional date issue in manual upload test
```
[ ] Yes
[ ] No
```
> PUB-2036 Fix functional date issue in manual upload test

- charts/pip-frontend/values.dev.template.yaml
- package.json
N/A
Increase memory allocation + remove debug
```
[ ] Yes
[x] No
```
> Increase memory allocation + remove debug

- package.json
- yarn.lock
N/A
Fixed vulnerability by updating optionator
```
[ ] Yes
[x] No
```
> Fixed vulnerability 

- src/test/end-to-end/shared/helpers/testingSupportApiHelper.ts
- src/test/end-to-end/shared/random-data.ts
- src/test/end-to-end/shared/testingSupportApi.ts
- src/test/end-to-end/tests/admin/create-new-account-test.ts
- src/test/end-to-end/tests/admin/manage-media-account-request-test.ts
- src/test/end-to-end/tests/admin/user-management-test.ts
- src/test/end-to-end/tests/system-admin/create-system-admin-test.ts
https://tools.hmcts.net/jira/browse/PUB-1986
```
[ ] Yes
[x] No
```
> PUB-1986 Update create system admin e2e tests

- Jenkinsfile_nightly
- charts/pip-frontend/values.dev.template.yaml
- wdio.conf.js
N/A
Updated a few things to fix the build pipeline:
1) Updated mem limits
2) Updated version of chrome driver
3) Updated nightly time
```
[ ] Yes
[x] No
```
> Updated nightly + mem limits + chrome driver version

- src/main/app.ts
- src/main/authentication/authentication.ts
- src/main/cacheManager.ts
- src/main/server.ts
https://tools.hmcts.net/jira/browse/PUB-2075
Fixed issue where app insights were not receiving the logs from the winston logger. This was due to the ordering of the imports (app insights must be imported first)
Also removed un-needed log statements
```
[ ] Yes
[x] No
```
> PUB-2075 - Fixed ordering issue with logging + removed uneeded logs

- src/main/resources/listLookup.json
- src/test/unit/mocks/listTypeSubscriptions/listTypeSubscriptions.json
- src/test/unit/service/publicationService.test.ts
- src/test/unit/service/subscriptionService.test.ts
- src/test/unit/views/subscription-configure-list.test.ts
https://tools.hmcts.net/jira/browse/PUB-1698
Update jurisdiction of SJP list to Magistrates
```
[ ] Yes
[x] No
```
> PUB-1698 Update jurisdiction of SJP list to Magistrates

- charts/pip-frontend/Chart.yaml
- charts/pip-frontend/values.stg.template.yaml
- charts/pip-frontend/values.yaml
https://tools.hmcts.net/jira/browse/PUB-2108
Increase the memory limits + cpu requests on the pods, so that it starts up first time and is consistent with Dev.
Also updated the staging pod dev limits (as part of the pipeline) to be consistent.
```
[ ] Yes
[x] No
```
> PUB-2108 - Increase limit + requests

- README.md
- src/main/service/listManipulation/SjpPressListService.ts
- src/main/service/listParseHelperService.ts
- src/test/unit/mocks/sjp-press-list.json
- src/test/unit/service/listManipulation/sjpPressListService.test.ts
- src/test/unit/views/single-justice-procedure-press.test.ts
https://tools.hmcts.net/jira/browse/PUB-1654
Handle SJP press list with missing address, individual forename and surname
```
[ ] Yes
[x] No
```
> PUB-1654 Handle SJP press list with missing address, forename and surname

- src/main/service/subscriptionService.ts
- src/main/views/subscription-configure-list.njk
- src/test/unit/service/subscriptionService.test.ts
- src/test/unit/views/subscription-configure-list.test.ts
https://tools.hmcts.net/jira/browse/PUB-1989
```
[ ] Yes
[ ] No
```
> PUB-1989 Update Welsh list name on Subscription Configure List page

- package.json
- wdio.conf.js
- yarn.lock
Use Chrome for Testing to auto integrate the e2e tests with the Chrome version
```
[ ] Yes
[x] No
```
> Use Chrome for Testing to auto integrate the e2e tests with the Chrome version

- src/main/resources/locales/bill/et-fortnightly-list.json
- src/main/resources/locales/cy/et-fortnightly-list.json
- src/main/resources/locales/en/et-fortnightly-list.json
- src/main/views/et-fortnightly-list.njk
- src/test/unit/mocks/etFortnightlyList.json
- src/test/unit/views/et-fortnightly-list.test.ts
https://tools.hmcts.net/jira/browse/PUB-2129
Remove Court Room name from fortnightly list
```
[ ] Yes
[x] No
```
> PUB-2129 - Remove court room name from ET Fortnightly

- src/main/resources/locales/bill/et-daily-list.json
- src/main/resources/locales/cy/et-daily-list.json
- src/main/resources/locales/en/et-daily-list.json
- src/main/views/et-daily-list.njk
- src/test/end-to-end/shared/mocks/etDailyList.json
- src/test/unit/mocks/etDailyList.json
- src/test/unit/service/listManipulation/etListsService.test.ts
- src/test/unit/views/et-daily-list.test.ts
- src/test/unit/views/et-fortnightly-list.test.ts
https://tools.hmcts.net/jira/browse/PUB-2128
Remove rep from ET Daily List
```
[ ] Yes
[x] No
```
> PUB-2128 - Removed Rep from ET Daily List

- src/main/controllers/CrownWarnedListController.ts
- src/main/resources/locales/bill/crown-warned-list.json
- src/main/resources/locales/cy/crown-warned-list.json
- src/main/resources/locales/en/crown-warned-list.json
- src/main/views/crown-warned-list.njk
- src/test/unit/controllers/CrownWarnedListController.test.ts
- src/test/unit/views/crown-warned-list.test.ts
https://tools.hmcts.net/jira/browse/PUB-1666
Crown Warned List clean-up
```
[ ] Yes
[x] No
```
> PUB-1666 Crown Warned List clean up

- src/main/controllers/CrownDailyListController.ts
- src/main/controllers/CrownWarnedListController.ts
- src/main/controllers/MagistratesPublicListController.ts
- src/main/controllers/MagistratesStandardListController.ts
- src/main/resources/locales/bill/magistrates-standard-list.json
- src/main/resources/locales/cy/magistrates-standard-list.json
- src/main/resources/locales/en/magistrates-standard-list.json
- src/main/service/listManipulation/CrimeListsService.ts
- src/main/service/listManipulation/MagistratesStandardListService.ts
- src/main/views/magistrates-standard-list.njk
- src/test/unit/controllers/MagistratesStandardListController.test.ts
- src/test/unit/mocks/address.json
- src/test/unit/service/listManipulation/crimeListsService.test.ts
- src/test/unit/service/listManipulation/magsStandardListService.test.ts
- src/test/unit/views/magistrates-standard-list.test.ts
https://tools.hmcts.net/jira/browse/PUB-1672
Magistrates Standard List clean up
```
[ ] Yes
[x] No
```
> PUB-1672 Magistrates Standard List clean up

- src/main/resources/locales/cy/accessibility-statement.json
- src/main/resources/locales/en/accessibility-statement.json
- src/main/views/accessibility-statement.njk
- src/test/unit/views/accessibility-statement.test.ts
https://tools.hmcts.net/jira/browse/PUB-2168
Update accessibility statement
```
[ ] Yes
[x] No
```
> PUB-2168 Update accessibility statement

- yarn.lock
N/A
Upgraded get-func-name version
```
[ ] Yes
[x] No
```
> Updated get-func-name version

- src/main/modules/helmet/index.ts
https://tools.hmcts.net/jira/browse/PUB-2145
Added dynatrace to content security policy
```
[ ] Yes
[x] No
```
> PUB-2145 Added dynatrace to content security policy

- package.json
- src/main/assets/scss/main.scss
- src/main/views/cookie-policy.njk
- src/main/views/macros/common-components.njk
- src/main/views/macros/sjp-common.njk
- src/main/views/subscription-management.njk
- yarn.lock
https://tools.hmcts.net/jira/browse/PUB-2006
Upgrade govuk frontend to v4.7.0
```
[ ] Yes
[x] No
```
> PUB-2006 Upgrade govuk frontend to v4.7.0

- package.json
- yarn.lock
N/A
Remove known issues file
```
[ ] Yes
[x] No
```
> Removed known issues file + updated postcss version

- src/test/end-to-end/shared/helpers/testingSupportApiHelper.ts
- src/test/end-to-end/shared/testingSupportApi.ts
- src/test/end-to-end/tests/system-admin/manage-third-party-users-test.ts
https://tools.hmcts.net/jira/browse/PUB-1833
Functional test added for E2E Test Feature - System Admin Dashboard - Manage Third-Party Users
```
[ ] Yes
[x] No
```
> Pub 1833 Manage Third-Party Users

- src/main/views/template.njk
- src/test/unit/views/delete-court-reference-data.test.ts
- src/test/unit/views/remove-list-search.test.ts
- src/test/unit/views/search.test.ts
https://tools.hmcts.net/jira/browse/PUB-2195
Added Dynatrace script.
```
[ ] Yes
[x] No
```
> PUB-2195 Added dynatrace script

- package.json
- yarn.lock
N/A
Update vulnerable dependency
```
[ ] Yes
[x] No
```
> Fix vulnurability in Babel

- package.json
- src/test/end-to-end/tests/single-justice-procedure-test.ts
- src/test/end-to-end/tests/verified/sjp-list-download-test.ts
https://tools.hmcts.net/jira/browse/PUB-2069
Increased window count for test run
```
[ ] Yes
[x] No
```
> Increased window count

- src/main/resources/locales/bill/crown-daily-list.json
- src/main/resources/locales/cy/crown-daily-list.json
- src/main/resources/locales/en/crown-daily-list.json
- src/main/views/crown-daily-list.njk
- src/test/unit/mocks/crownDailyList.json
- src/test/unit/views/crown-daily-list.test.ts
https://tools.hmcts.net/jira/browse/PUB-2017
Add reporting restriction detail for the Crown Daily list
```
[ ] Yes
[x] No
```
> PUB-2017 - Reporting restrictions for Crown Daily list

- src/main/controllers/SjpPressListController.ts
- src/main/resources/locales/bill/single-justice-procedure-press.json
- src/main/resources/locales/cy/single-justice-procedure-press.json
- src/main/resources/locales/en/single-justice-procedure-press.json
- src/main/views/single-justice-procedure-press.njk
- src/test/unit/controllers/SjpPressListController.test.ts
- src/test/unit/views/single-justice-procedure-press.test.ts
https://tools.hmcts.net/jira/browse/PUB-2161
Add Important Info to SJP Lists
```
[ ] Yes
[x] No
```
> PUB-2161 - Add Important Info to SJP Lists

- src/main/helpers/infoProvider.ts
- src/test/unit/views/info.test.ts
https://tools.hmcts.net/jira/browse/PUB-2210
Removed uptime from Info endpoint
```
[ ] Yes
[x] No
```
> PUB-2210 - Removed uptime from info endpoint

- src/main/resources/locales/cy/sign-in.json
- src/main/resources/locales/en/sign-in.json
- src/test/unit/views/sign-in.test.ts
https://tools.hmcts.net/jira/browse/PUB-2235
Updated common platform message on sign in
```
[ ] Yes
[x] No
```
> PUB-2235 - Updated common platform message

- src/main/resources/locales/cy/home.json
- src/main/resources/locales/en/home.json
- src/test/unit/views/home.test.ts
https://tools.hmcts.net/jira/browse/PUB-2236
Updated link to NI Court and Tribunals site
```
[ ] Yes
[x] No
```
> PUB-2236 - Updated Link

- src/main/routes/routes.ts
- src/test/routes/subscription-configure-list-confirmed.test.ts
https://tools.hmcts.net/jira/browse/PUB-2001
Added authentication on the subscription configure list confirmed screen
```
[ ] Yes
[x] No
```
> PUB-2001 - Fix configure list confirmation screen

- src/test/end-to-end/shared/mocks/civilAndFamilyDailyCauseList.json
- src/test/unit/controllers/MagistratesStandardListController.test.ts
- src/test/unit/mocks/civilAndFamilyDailyCauseList.json
- src/test/unit/mocks/crownDailyList.json
- src/test/unit/mocks/dailyCauseEmptyCourtList.json
- src/test/unit/mocks/dailyCauseList.json
- src/test/unit/mocks/familyDailyCauseList.json
- src/test/unit/mocks/familyDailyCauseListPartyMapping.json
- src/test/unit/mocks/magsStandardList.json
- src/test/unit/service/listManipulation/magsStandardListService.test.ts
- src/test/unit/views/civil-and-family-daily-cause-list.test.ts
- src/test/unit/views/daily-cause-list.test.ts
- src/test/unit/views/family-daily-cause-list.test.ts
- src/test/unit/views/magistrates-standard-list.test.ts
- src/test/unit/views/sscs-daily-list-test.ts
https://tools.hmcts.net/jira/browse/<PR-name-here>
```
[ ] Yes
[x] No
```
> PUB-2090 Clean up test data

- README.md
- charts/pip-frontend/Chart.yaml
- charts/pip-frontend/values.dev.template.yaml
- charts/pip-frontend/values.yaml
https://tools.hmcts.net/jira/browse/PUB-2245
Updated README + Removed unused value
```
[ ] Yes
[x] No
```
> PUB-2245 - Updated README

- yarn.lock
N/A
Updated library to fix vulnurability
```
[ ] Yes
[x] No
```
> Updated follow redirects

- src/main/resources/locales/cy/accessibility-statement.json
- src/main/resources/locales/cy/account-request-submitted.json
- src/main/resources/locales/cy/cookie-policy.json
https://tools.hmcts.net/jira/browse/PUB-2268
Updating GLlTEM to GLlTEF
```
[ ] Yes
[x] No
```
> Updating GLlTEM to GLlTEF

- src/main/views/template.njk
https://tools.hmcts.net/jira/browse/PUB-2317
Updated to new version of Crown
```
[ ] Yes
[x] No
```
> PUB-2317 - Updated to new crown logo

- src/main/service/listManipulation/SscsDailyListService.ts
- src/test/unit/mocks/sscsDailyList.json
- src/test/unit/service/listManipulation/sscsListService.test.ts
- src/test/unit/views/sscs-daily-list-test.ts
-   [ ] commit messages are meaningful and follow good commit message guidelines
-   [ ] README and other documentation has been updated / added (if needed)
-   [x] tests have been updated / new tests has been added (if needed)
https://tools.hmcts.net/jira/browse/PUB-2341
https://tools.hmcts.net/jira/browse/<PR-name-here>
```
[ ] Yes
[x] No
```
> Pub 2341 remove informant from sscs daily lists

- package.json
- src/test/end-to-end/shared/mocks/etDailyList.json
- src/test/end-to-end/shared/mocks/invalidEtDailyList.json
- src/test/end-to-end/tests/admin/manual-upload-json-test.ts
- src/test/end-to-end/tests/custom-steps.ts
- yarn.lock
Fix build pipeline
Fix build pipeline
```
[ ] Yes
[x] No
```
> Fix build pipeline

- src/main/service/listManipulation/SscsDailyListService.ts
- src/main/service/listParseHelperService.ts
- src/test/unit/mocks/hearingparty/sscsDailyList.json
- src/test/unit/mocks/sscsDailyList.json
- src/test/unit/service/listManipulation/hearingparty/sscsListService.test.ts
- src/test/unit/service/listManipulation/sscsListService.test.ts
https://tools.hmcts.net/jira/browse/PUB-2344
Fixed two issues:
- If there were two sittings, and the second sittings channel was empty, it would not use the session channel
- If there were was a sitting, but the sittings channel was empty and session channel was not present it would crash
```
[ ] Yes
[x] No
```
> PUB-2344 - Fixed SSCS bug

- package.json
- yarn.lock
Force upgrade of express to 4.19.2
```
[ ] Yes
[x] No
```
> Force upgrade of express to 4.19.2

- src/test/end-to-end/tests/verified/sjp-list-download-test.ts
Update SJP list download e2e test
```
[ ] Yes
[x] No
```
> Update SJP list download e2e test

- src/main/views/style-guide/single-justice-procedure-press.njk
-   [X] commit messages are meaningful and follow good commit message guidelines
-   [X] README and other documentation has been updated / added (if needed)
-   [X] tests have been updated / new tests has been added (if needed)
https://tools.hmcts.net/jira/browse/PUB-2165
https://tools.hmcts.net/jira/browse/<PR-name-here>
```
[ ] Yes
[X] No
```
> PUB-2165 - Modified single-justice-procedure-press.njk

- src/test/end-to-end/shared/testingSupportApi.ts
- src/test/end-to-end/tests/a-z-list-courts-and-tribunals-test.ts
- src/test/end-to-end/tests/admin/remove-list-test.ts
- src/test/end-to-end/tests/single-justice-procedure-test.ts
- src/test/end-to-end/tests/sorting-list-table-test.ts
- src/test/end-to-end/tests/system-admin/blob-explorer-test.ts
- src/test/end-to-end/tests/system-admin/delete-court-test.ts
- src/test/end-to-end/tests/unverified-user-end-to-end-journey-test.ts
- src/test/end-to-end/tests/verified/email-subscriptions-test.ts
- src/test/end-to-end/tests/verified/single-justice-procedure-cases-test.ts
- src/test/end-to-end/tests/verified/sjp-list-download-test.ts
https://tools.hmcts.net/jira/browse/PUB-2432
Update SJP e2e tests to use future content date
```
[ ] Yes
[x] No
```
> Update SJP e2e tests to use future content date

- src/test/end-to-end/tests/admin/create-new-account-test.ts
- src/test/end-to-end/tests/admin/manual-upload-json-test.ts
- src/test/end-to-end/tests/admin/user-management-test.ts
- src/test/end-to-end/tests/login-test.ts
- src/test/end-to-end/tests/system-admin/bulk-create-media-accounts-test.ts
- src/test/end-to-end/tests/system-admin/create-system-admin-test.ts
- src/test/end-to-end/tests/system-admin/delete-court-test.ts
- src/test/end-to-end/tests/system-admin/upload-reference-data-test.ts
https://tools.hmcts.net/jira/browse/PUB-2477
Flag e2e tests as nightly tests
```
[ ] Yes
[x] No
```
> PUB-2477 Flag e2e tests as nightly tests

- yarn.lock
N/A
Fixed dependency version in yarn lock file
```
[ ] Yes
[x] No
```
> Fixed dependency version

- src/main/resources/locales/en/magistrates-standard-list.json
https://tools.hmcts.net/jira/browse/PUB-2595
Updated to Hearing Type for mags standard list. Welsh translation already appears to be correct.
```
[ ] Yes
[x] No
```
> PUB-2595 - Updated hearing type

- src/test/end-to-end/tests/system-admin/user-management-test.ts
N/A
Fixed Admin tests
```
[ ] Yes
[x] No
```
> Fix E2E Tests Admin

- src/main/views/admin/remove-list-search-results.njk
https://tools.hmcts.net/jira/browse/PUB-2651
Fix AXE findings for Admin
```
[ ] Yes
[x] No
```
> PUB-2561 - Fix AXE findings

- src/main/resources/locales/cy/sso-rejected-login.json
- src/main/resources/locales/en/sso-rejected-login.json
- src/main/views/sso-rejected-login.njk
- src/test/unit/views/sso-rejected-login.test.ts
https://tools.hmcts.net/jira/browse/PUB-2664
Add ServiceNow link to SSO rejected login page
```
[ ] Yes
[x] No
```
> PUB-2664 Add ServiceNow link to SSO rejected login page

- package.json
- src/test/accessibility/accessibility-admin-test.ts
- yarn.lock
https://tools.hmcts.net/jira/browse/PUB-2699
Updated dependency and accessibility test
```
[ ] Yes
[x] No
```
> PUB-2699 - Updated dependency + tests

- src/main/modules/i18next/index.ts
- src/test/unit/views/home.test.ts
https://tools.hmcts.net/jira/browse/PUB-2698
Added HTML Lang attribute to ensue the HTML tag is set correctly
```
[ ] Yes
[x] No
```
> PUB-2698 - Updated language

- src/main/resources/listLookup.json
- src/test/unit/service/ManualUploadService.test.ts
- src/test/unit/service/PublicationService.test.ts
https://tools.hmcts.net/jira/browse/PUB-2712
Add CIC Daily Hearing List
```
[ ] Yes
[x] No
```
> PUB-2712 Add CIC Daily Hearing List

- src/main/modules/i18next/index.ts
- src/test/unit/views/home.test.ts
N/A
Merge freeze into master
```
[ ] Yes
[x] No
```
> Merge freeze into master

- src/main/views/admin/manual-upload-summary.njk
- src/test/unit/views/admin/manual-upload-summary.test.ts
https://tools.hmcts.net/jira/browse/PUB-2735
Fix issue with missing query parameter on change link
```
[ ] Yes
[x] No
```
> PUB-2735 - Adding query param to change button for non strategic

- src/main/resources/locales/cy/delete-court-reference-data-confirmation.json
- src/main/resources/locales/cy/remove-list-confirmation.json
- src/main/resources/locales/en/delete-court-reference-data-confirmation.json
- src/main/resources/locales/en/remove-list-confirmation.json
- src/main/views/admin/remove-list-confirmation.njk
- src/main/views/system-admin/delete-court-reference-data-confirmation.njk
- src/test/unit/views/admin/remove-list-confirmation.test.ts
- src/test/unit/views/system-admin/delete-court-reference-data-confirmation.test.ts
https://tools.hmcts.net/jira/browse/PUB-2175
Fixed ordering of headers and removed warning text on Remove Content and Delete Court page
```
[ ] Yes
[x] No
```
> PUB-2175 - Fixed header location + removed warning text

- src/test/end-to-end/tests/custom-steps.ts
- src/test/end-to-end/tests/login-test.ts
- src/test/end-to-end/tests/system-admin/manage-third-party-users-test.ts
- src/test/end-to-end/tests/verified/email-subscriptions-test.ts
https://tools.hmcts.net/jira/browse/PUB-2774
Add wait after e2e test login
```
[ ] Yes
[x] No
```
> PUB-2774 Add wait after e2e test login

- src/main/resources/locales/cy/home.json
- src/main/resources/locales/en/home.json
- src/test/end-to-end/tests/unverified-user-end-to-end-journey-test.ts
- src/test/unit/views/home.test.ts
https://tools.hmcts.net/jira/browse/PUB-2770
Updated text on the interstitial page
```
[ ] Yes
[x] No
```
> PUB-2770 - Interstitial pages

- src/main/controllers/SsoRejectedLoginController.ts
- src/test/routes/sso-rejected-login.test.ts
- src/test/unit/controllers/SsoRejectedLoginController.test.ts
https://tools.hmcts.net/jira/browse/PUB-2654
Redirect to 'not found' page if user attempts to access SSO rejected login page directly
```
[ ] Yes
[x] No
```
> PUB-2654 - SSO rejected login page error message

- src/main/controllers/SummaryOfPublicationsController.ts
- src/main/models/AdditionalLocationInfo.ts
- src/main/resources/additionalLocationInfoLookup.json
- src/main/service/LocationService.ts
- src/main/views/summary-of-publications.njk
- src/test/unit/controllers/SummaryOfPublicationsController.test.ts
- src/test/unit/service/LocationService.test.ts
- src/test/unit/views/summary-of-publications.test.ts
https://tools.hmcts.net/jira/browse/PUB-2737
Add no list message override for Mental Health Tribunal
```
[ ] Yes
[x] No
```
> PUB-2737 Add no list message override for Mental Health Tribunal

- src/test/end-to-end/tests/admin/manual-upload-non-strategic-test.ts
https://tools.hmcts.net/jira/browse/<PR-name-here>
Temporarily remove non-strategic list type check in e2e test
```
[ ] Yes
[x] No
```
> Temporarily remove non-strategic list type check in e2e test

- src/test/end-to-end/tests/admin/manual-upload-non-strategic-test.ts
Remove list type check in e2e test
```
[ ] Yes
[x] No
```
> Remove list type check in e2e test

- yarn.lock
N/A
Updated babel dependency used by i18next
```
[ ] Yes
[x] No
```
> Updated babel for i18next

- src/test/unit/requests/dataManagementRequests.test.ts
N/A
Added test for data management request
```
[ ] Yes
[x] No
```
> Added test for Data Management request

- jest.config.js
N/A
Updated test coverage
```
[ ] Yes
[x] No
```
> Updated test coverage

- package.json
- src/test/end-to-end/tests/login-test.ts
https://tools.hmcts.net/jira/browse/PUB-2982
Do not run Crime Idam tests on PR stage
[ ] Yes
[x] No
> PUB-2892 Do not run Crime Idam tests on PR stage

- src/main/assets/scss/main.scss
https://tools.hmcts.net/jira/browse/PUB-2419
Remove custom beta link styling
```
[ ] Yes
[x] No
```
> PUB-2419 Remove custom beta link styling

- charts/pip-frontend/values.stg.template.yaml
> fix crime test
